name: 📦 Track Bundle Size

on:
  pull_request:
    branches:
      - main
      - develop

jobs:
  compress-size:
    name: 🚀 Check Bundle Size
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout Repository
        uses: actions/checkout@v4

      - name: 🏗️ Setup Node.js & pnpm
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: 📦 Install pnpm
        run: npm install -g pnpm

      - name: 📦 Install Dependencies
        run: pnpm install --no-frozen-lockfile

      - name: 🔨 Build Project
        run: pnpm run build

      - name: 📦 Check Bundle Size
        uses: preactjs/compressed-size-action@v2
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          pattern: "dist/*.{cjs,mjs}"
